insight/insight/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("prospect.urls")),
    path("admin/", admin.site.urls),
]

insight/prospect/urls.py
from django.urls import path

from . import views

app_name = "prospect"
urlpatterns = [
    path("", views.index, name="index"),
    path("report/<uuid:report_tag>/", views.report, name="report"),
    path("add", views.add_prospect, name="add"),
    path("analyse", views.generate_report, name="analyse"),
    path("status", views.check_report_status, name="status"),
]

insight/prospect/models.py
from django.db import models


class Prospect(models.Model):
    name = models.CharField(max_length=200, unique=True)
    reports = models.IntegerField(default=0)
    last = models.DateTimeField(auto_now=True)
    last_tag = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    @classmethod
    def update_last_report(cls, tag):
        """Update the prospect row's number of reports and last time generated
        The timestamp is updated every time the row is touched
        """
        report = Report.objects.get(tag=tag)
        prospect = report.prospect
        prospect.reports += 1
        prospect.last_tag = tag
        prospect.save()


class Report(models.Model):
    prospect = models.ForeignKey(Prospect, on_delete=models.CASCADE)
    main_url = models.URLField(max_length=200)
    comp1_name = models.CharField(max_length=200, default="Competitor")
    comp1_url = models.URLField(max_length=200)
    comp2_name = models.CharField(max_length=200, default="Competitor")
    comp2_url = models.URLField(max_length=200)
    device_type = models.CharField(max_length=10, default="Desktop")
    date = models.DateTimeField(auto_now_add=True)
    tag = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return f"Report for {self.prospect} generated on {self.date}"

    @classmethod
    def create_by_tag(cls, prospect_name, comp1_name, comp2_name, urls, device, tag):
        """Creates a report """
        prospect = Prospect.objects.get(name=prospect_name)
        main_url, comp1_url, comp2_url = urls
        cls.objects.create(
            prospect=prospect,
            main_url=main_url,
            comp1_name=comp1_name,
            comp1_url=comp1_url,
            comp2_name=comp2_name,
            comp2_url=comp2_url,
            device_type=device,
            tag=tag
        )

insight/prospect/views.py
from uuid import uuid4

from django.db import IntegrityError
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages

from prospect.models import Prospect, Report
from prospect.queue import schedule_report, q as queue
from prospect.s3 import get_json_reports


def index(request):
    context = {"prospects": Prospect.objects.all()}
    return render(request, "prospect/index.html", context)


def report(request, report_tag):

    rep = Report.objects.get(tag=report_tag)

    reports_data = get_json_reports(rep)

    context = {
        "prospect": rep.prospect.name,
        "comp1": rep.comp1_name,
        "comp2": rep.comp2_name,
        "reports": reports_data,
        "device": rep.device_type,
        "tag": report_tag
    }
    return render(request, "prospect/report.html", context)


def add_prospect(request):

    name = request.POST.get("name", "")

    if name:
        try:
            Prospect.objects.create(name=name)
        except IntegrityError:
            messages.error(request, f"A prospect already exist called {name}")

    return HttpResponseRedirect(reverse("prospect:index"))


def generate_report(request):

    if request.session.get("ongoing_report"):
        messages.info(request, "You already have a running report, wait for it to finish before starting a new one.")
        return HttpResponseRedirect(reverse("prospect:index"))

    # Get parameters from the form
    prospect = request.POST.get("prospect", "")
    comp_one_name = request.POST.get("comp1name", "")
    comp_two_name = request.POST.get("comp2name", "")
    prospect_url = request.POST.get("prospecturl", "")
    comp_one_url = request.POST.get("comp1url", "")
    comp_two_url = request.POST.get("comp2url", "")
    device = request.POST.get("devicetype", "")

    # Create a unique tag
    tag = uuid4()

    # Add reports to the queue to be picked up by workers
    main, comp1, comp2 = schedule_report([prospect_url, comp_one_url, comp_two_url], device, tag, prospect)

    # Store session information
    request.session["ongoing_report"] = True
    request.session["main_id"] = main
    request.session["comp1_id"] = comp1
    request.session["comp2_id"] = comp2
    request.session["tag"] = str(tag)

    # Update db
    Report.create_by_tag(
        prospect,
        comp_one_name,
        comp_two_name,
        [prospect_url, comp_one_url, comp_two_url],
        device,
        tag
    )

    messages.info(request, "Your report is being prepared!")
    return HttpResponseRedirect(reverse("prospect:index"))


def check_report_status(request):

    #  Retrieve session info
    main = request.session.get("main_id")
    comp1 = request.session.get("comp1_id")
    comp2 = request.session.get("comp2_id")
    tag = request.session.get("tag")
    jobs = [main, comp1, comp2]

    if {main, comp1, comp2}.issubset(queue.finished_job_registry.get_job_ids()):
        messages.info(request, "Your report is ready!")
        Prospect.update_last_report(tag)

    elif {main, comp1, comp2}.issubset(queue.failed_job_registry.get_job_ids()):
        messages.info(request, "There has been a problem creating your report.")

    elif any(job in jobs for job in queue.scheduled_job_registry.get_job_ids()):
        return JsonResponse({"response": "Your report is waiting to be processed", "status": "Busy"})
    elif any(job in jobs for job in queue.started_job_registry.get_job_ids()):
        return JsonResponse({"response": "Your report is being processed", "status": "Busy"})
    elif any(job in jobs for job in queue.deferred_job_registry.get_job_ids()):
        return JsonResponse({"response": "Your report has been deferred", "status": "Busy"})
    else:
        messages.info(request, "We were unable to find your report request")

    # If the job is finished or failed or we can't find it, flush the session and free the user.
    request.session.flush()
    return JsonResponse({"response": "Free to go!", "status": "Available"})

insight/prospect/templates/prospect/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Prospect Insighter</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href='{% static "css/bootstrap.css" %}'>
    <script src='{% static "js/bootstrap.js" %}'></script>
    <link rel="stylesheet" href='{% static "css/mainStyles.css" %}'>
    <script src='{% static "js/mainFunctions.js" %}'></script>
</head>
<body>

    <div class="row container justify-content-center m-auto">
        <a href="{% url 'prospect:index' %}">
            <img src="https://scivisum-email-static-content.s3-eu-west-1.amazonaws.com/Tribe+Logo.png" alt="ThinkTribe Logo" id="tribe-logo" class="img-responsive my-3" width="120" height="auto">
        </a>
    </div>

    <div class="row">
        <hr class="mt-2 col-6">
    </div>

    <div class="row container justify-content-center m-auto mt-4">
        <h1 class="text-tribe">{% block title %}Prospects Insight{% endblock %}</h1>
    </div>

{% block body %}{% endblock %}
</body>
</html>

insight/prospect/templates/prospect/index.html
{% extends "prospect/base.html" %}

{% block body %}

    <section class="container text-center mt-3">

        <nav class="navbar navbar-expand-sm navbar-light justify-content-center rounded mt-2">

            <form class="form-inline" action="{% url 'prospect:analyse' %}" method="post">
                {% csrf_token %}

                <div class="row">

                    <div class="col">

                        <div class="row">
                            <div class="col-9 form-group mb-1 pr-0">
                                <select name="prospect" class="form-control max-width" required>
                                    <option disabled selected>Prospect</option>
                                    {% for prospect in prospects %}
                                    <option value="{{ prospect.name }}">{{ prospect.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col pl-0">
                                <button type="button" class="btn btn-tribe" data-toggle="modal" data-target="#add-new-prospect">+</button>
                            </div>
                        </div>

                        <input pattern="http(s?)(:\/\/)((www.)?)(([^.]+)\.)?([a-zA-z0-9\-_]+)(.co.uk|.com|.net|.gov|.org|.in)(\/[^\s]*)?" id="prospect-url" class="form-control max-width" type="url" name="prospecturl" placeholder="Prospect URL" required>
                    </div>

                    <div class="col">

                        <input id="compone-name" class="form-control mr-sm-2 mb-1 max-width" type="text" name="comp1name" placeholder="Competitor Name" required>

                        <input pattern="http(s?)(:\/\/)((www.)?)(([^.]+)\.)?([a-zA-z0-9\-_]+)(.co.uk|.com|.net|.gov|.org|.in)(\/[^\s]*)?" id="compone-url" class="form-control mr-sm-2 max-width" type="url" name="comp1url" placeholder="Competitor URL" required>

                    </div>

                    <div class="col">

                        <input id="comptwo-name" class="form-control mr-sm-2 mb-1 max-width" type="text" name="comp2name" placeholder="Competitor Name" required>

                        <input pattern="http(s?)(:\/\/)((www.)?)(([^.]+)\.)?([a-zA-z0-9\-_]+)(.co.uk|.com|.net|.gov|.org|.in)(\/[^\s]*)?" id="comptwo-url" class="form-control mr-sm-2 max-width" type="url" name="comp2url" placeholder="Competitor URL" required>

                    </div>

                    <div class="col my-auto">
                        <select name="devicetype" class="form-control max-width" required>
                            <option disabled selected>Device Type</option>
                            <option value="mobile">Mobile</option>
                            <option value="desktop">Desktop</option>
                        </select>
                    </div>

                    <div class="col my-auto">
                        <button class="btn btn-tribe max-width" type="submit">Analyse</button>
                    </div>
                </div>
            </form>

            <!-- The Modal -->
            <div class="modal fade mt-5 border-0" id="add-new-prospect">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title text-tribe">Add New Prospect</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body ">
                            <form class="form-inline" action="{% url 'prospect:add' %}" method="post">
                                {% csrf_token %}
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="name" placeholder="Prospect">
                                        <button class="btn btn-tribe ml-2" type="submit">Add</button>
                                    </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>

        </nav>

    </section>

    <section id="prospect-listing-table" class="justify-content-center">

        <div class="row">
            <hr class="mt-5 col-6">
        </div>

        <div class="row container justify-content-center m-auto">
            <h3 class="text-tribe">Prospect Reports</h3>
        </div>

        <div class="container mt-3">

            <input class="form-control my-2" id="prospect-table-search" type="text" placeholder="Quick filter..">

            <table class="table table-hover table-light border rounded">
                <thead id="prospect-table-header" class="table-light border">
                  <tr>
                    <th>Prospect</th>
                    <th>Reports</th>
                    <th>Last Run</th>
                  </tr>
                </thead>
                <tbody id="prospect-table-body" class="rounded">
                    {% for prospect in prospects %}
                      <tr>
                        <td>{{ prospect.name }}</td>
                        <td>{{ prospect.reports }}</td>

                        <td>
                            {% if prospect.last_tag %}
                                <a href="{% url 'prospect:report' prospect.last_tag %}">{{ prospect.last }}</a>
                            {% endif %}
                        </td>
                      </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </section>


    <section class="justify-content-center">

        <div class="container mt-3">

            <table class="table table-hover table-light border rounded">
                <thead class="table-light border">
                  <tr>
                    <th>Engine Status</th>
                    <th>Engine Message</th>

                  </tr>
                </thead>
                <tbody class="rounded">
                  <tr>
                    {% if request.session.ongoing_report %}
                        <td id="busy-status">Busy</td>
                    {% else %}
                        <td id="available-status">Available</td>
                    {% endif %}
                        <td id="message"></td>
                  </tr>

                </tbody>
            </table>
        </div>

    </section>

    {% if messages %}
        {% for message in messages %}
            <script>
                alert("{{ message }}");
            </script>
        {% endfor %}
    {% endif %}

    {% if request.session.ongoing_report %}
    <script>
        (function poll() {
        setTimeout(function() {
            $.ajax({
                url: "{% url 'prospect:status' %}",
                type: "GET",
                success: function(data) {
                    $("#status").text(data["status"])
                    $("#message").text(data["response"])
                    if (data["status"] == "Available"){
                        location.reload(true);
                    }
                },
                dataType: "json",
                complete: poll,
                timeout: 2000
            })
        }, 10000);
        })();
    </script>
    {% endif %}

{% endblock %}

insight/prospect/templates/prospect/report.html
{% extends "prospect/base.html" %}

{% block title %}{{ prospect }} Performance Report{% endblock %}

{% block body %}

    <section id="prospect-listing-table" class="justify-content-center">

        <div class="row">
            <hr class="mt-3 col-6">
        </div>

        <div class="container mt-3">

            <table class="table table-hover table-light border rounded">
                <thead id="report-table-header" class="table-light border">
                <tr>
                    <th style="width: 40%">Metric</th>
                    <th><a href="../../reports/{{ tag }}-main.report.html">{{ prospect }}</a></th>
                    <th><a href="../../reports/{{ tag }}-comp1.report.html">{{ comp1 }}</a></th>
                    <th><a href="../../reports/{{ tag }}-comp2.report.html">{{ comp2 }}</a></th>
                </tr>
                </thead>
                <tbody id="report-table-body">
                    <tr>
                        <td>Performance Score</td>
                        {% for report in reports%}
                        <td class="badge-{{ report.performance_class }}">{{ report.performance_score }}</td>
                        {% endfor %}
                    </tr>
                    <tr>
                        <td>First Contentful Paint</td>
                        {% for report in reports%}
                        <td class="text-{{ report.metrics.first_contentful_paint.perf_class }}">{{ report.metrics.first_contentful_paint.timing }}</td>
                        {% endfor %}
                    </tr>
                    <tr>
                        <td>Speed Index</td>
                        {% for report in reports%}
                        <td class="text-{{ report.metrics.speed_index.perf_class }}">{{ report.metrics.speed_index.timing }}</td>
                        {% endfor %}
                    </tr>
                    <tr>
                        <td>Largest Contentful Paint</td>
                        {% for report in reports%}
                        <td class="text-{{ report.metrics.largest_contentful_paint.perf_class }}">{{ report.metrics.largest_contentful_paint.timing }}</td>
                        {% endfor %}
                    </tr>
                    <tr>
                        <td>Time to Interactive</td>
                        {% for report in reports%}
                        <td class="text-{{ report.metrics.interactive.perf_class }}">{{ report.metrics.interactive.timing }}</td>
                        {% endfor %}
                    </tr>
                    <tr>
                        <td>Total Blocking Time</td>
                        {% for report in reports%}
                        <td class="text-{{ report.metrics.total_blocking_time.perf_class }}">{{ report.metrics.total_blocking_time.timing }}</td>
                        {% endfor %}
                    </tr>
                    <tr>
                        <td>Cumulative Layout Shift</td>
                        {% for report in reports%}
                        <td class="text-{{ report.metrics.cumulative_layout_shift.perf_class }}">{{ report.metrics.cumulative_layout_shift.timing }}</td>
                        {% endfor %}

                    </tr>
                </tbody>
            </table>
        </div>

    </section>

{% endblock %}